version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: requirements.txt

mkdocs:
  configuration: ./mkdocs.yaml
