name: Checks

on:
  pull_request:
  push:
    branches: [main]

env:
    PYTHON_VERSION: 3.12.9
    UV_VERSION: 0.6.9

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
    cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - uses: DavidAnson/markdownlint-cli2-action@v19 # https://github.com/DavidAnson/markdownlint-cli2-action
        with:
          globs: '**/*.md'

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        id: setup-python
        uses: actions/setup-python@v5 # https://github.com/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv ${{ env.UV_VERSION }}
        uses: astral-sh/setup-uv@v5 # https://github.com/astral-sh/setup-uv
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build mkdocs
        run: uv run mkdocs build -d dist
